/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-19 05:08:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.panacea.patient.model.vo.*;
import com.panacea.doctor.model.vo.*;
import com.panacea.admin.model.vo.*;
import com.panacea.doctor.model.vo.*;

public final class adminDoctorView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1526547638000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1525785638000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("com.panacea.admin.model.vo");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.panacea.doctor.model.vo");
    _jspx_imports_packages.add("com.panacea.patient.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");

	String selected_menu = (String)request.getAttribute("selectedMenu");
	String selected_submenu = (String)request.getAttribute("selectedSubMenu");

      out.write('\r');
      out.write('\n');

	String loginType = (String)session.getAttribute("loginType");
	System.out.println("sessionLoginType="+loginType);

	Patient loginPatient = null;
	Doctor loginDoctor = null;
	Admin loginAdmin = null;	

	boolean isLogin = false;
	
	if("patient".equals(loginType)){
		loginPatient = (Patient)session.getAttribute("loginPatient");
		/* System.out.println("sessionLoginId="+loginPatient.getPatientId()); */
		isLogin = true;
	} else if("doctor".equals(loginType)){
		loginDoctor = (Doctor)session.getAttribute("loginDoctor");
		/* System.out.println("sessionLoginId="+loginDoctor.getDoctorId()); */
		isLogin = true;
	} else if("admin".equals(loginType)){
		loginAdmin = (Admin)session.getAttribute("loginAdmin");
		/* System.out.println("sessionLoginId="+loginAdmin.getAdminId()); */
		isLogin = true;
	}

	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>PANACEA</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Do+Hyeon|Didact+Gothic\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\".menu\").each(function(){\r\n");
      out.write("\t\t\tif($(this).hasClass(\"");
      out.print(selected_menu);
      out.write("\")){\r\n");
      out.write("\t\t\t\t$(this).find(\"a\").css({\r\n");
      out.write("\t\t\t\t\t\"border-bottom\":\"5px solid #00165e\",\r\n");
      out.write("\t\t\t\t\t\"padding-bottom\": \"10px\",\r\n");
      out.write("\t\t\t\t\t\"color\":\"#00165e\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".submenu\").each(function(){\r\n");
      out.write("\t\t\tif($(this).hasClass(\"");
      out.print(selected_submenu);
      out.write("\")){\r\n");
      out.write("\t\t\t\t$(this).css({\r\n");
      out.write("\t\t\t\t\t\"background-image\": \"url('../img/subnav_back.png')\",\r\n");
      out.write("\t\t\t    \t\"background-repeat\": \"no-repeat\",\r\n");
      out.write("\t\t\t    \t\"background-position\": \"right\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(this).find(\"a\").css({\r\n");
      out.write("\t\t\t\t\t\"color\": \"#3954ad\",\r\n");
      out.write("\t\t\t    \t\"text-decoration\": \"underline\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".stepmenu\").each(function(){\r\n");
      out.write("\t\t\tvar div_id = $(this).attr(\"id\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(div_id == \"step1\" && div_id == \"");
      out.print(selected_submenu);
      out.write("\"){\r\n");
      out.write("\t\t\t\t$(this).css({\r\n");
      out.write("\t\t\t\t\t\"background\":\"#fbfbfb\",\r\n");
      out.write("\t\t\t\t\t\"color\":\"#6480db\",\r\n");
      out.write("\t\t\t\t\t\"border-top\":\"1px solid #6480db\",\r\n");
      out.write("\t\t\t\t\t\"border-left\":\"1px solid #6480db\",\r\n");
      out.write("\t\t\t\t\t\"border-right\":\"1px solid #6480db\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#step2\").css({\r\n");
      out.write("\t\t\t\t\t\"background\": \"#2f4488\",\r\n");
      out.write("\t\t\t\t\t\"color\": \"white\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#step3\").css({\r\n");
      out.write("\t\t\t\t\t\"background\": \"#04185b\",\r\n");
      out.write("\t\t\t\t\t\"color\": \"white\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#reservation-content\").css(\"border-color\", \"#6480db\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(div_id == \"step2\" && div_id == \"");
      out.print(selected_submenu);
      out.write("\"){\r\n");
      out.write("\t\t\t\t$(this).css({\r\n");
      out.write("\t\t\t\t\t\"background\":\"#fbfbfb\",\r\n");
      out.write("\t\t\t\t\t\"color\":\"#2f4488\",\r\n");
      out.write("\t\t\t\t\t\"border-top\":\"1px solid #2f4488\",\r\n");
      out.write("\t\t\t\t\t\"border-left\":\"1px solid #2f4488\",\r\n");
      out.write("\t\t\t\t\t\"border-right\":\"1px solid #2f4488\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#step1\").css({\r\n");
      out.write("\t\t\t\t\t\"background\": \"#6480db\",\r\n");
      out.write("\t\t\t\t\t\"color\": \"white\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#step3\").css({\r\n");
      out.write("\t\t\t\t\t\"background\": \"#04185b\",\r\n");
      out.write("\t\t\t\t\t\"color\": \"white\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#reservation-content\").css(\"border-color\", \"#2f4488\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(div_id == \"step3\" && div_id == \"");
      out.print(selected_submenu);
      out.write("\"){\r\n");
      out.write("\t\t\t\t$(this).css({\r\n");
      out.write("\t\t\t\t\t\"background\":\"#fbfbfb\",\r\n");
      out.write("\t\t\t\t\t\"color\":\"#04185b\",\r\n");
      out.write("\t\t\t\t\t\"border-top\":\"1px solid #04185b\",\r\n");
      out.write("\t\t\t\t\t\"border-left\":\"1px solid #04185b\",\r\n");
      out.write("\t\t\t\t\t\"border-right\":\"1px solid #04185b\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#step1\").css({\r\n");
      out.write("\t\t\t\t\t\"background\": \"#6480db\",\r\n");
      out.write("\t\t\t\t\t\"color\": \"white\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#step2\").css({\r\n");
      out.write("\t\t\t\t\t\"background\": \"#2f4488\",\r\n");
      out.write("\t\t\t\t\t\"color\": \"white\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#reservation-content\").css(\"border-color\", \"#04185b\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("<body>\r\n");
      out.write("\t<header id = \"header\">\r\n");
      out.write("\t\t<div id=\"title-wrapper\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\">\r\n");
      out.write("\t\t\t\t<img class=\"logo\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" alt=\"logo_panacea\" />\r\n");
      out.write("\t\t\t\t<h1 id=\"title\">Panacea</h1>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("  \t\t<nav id=\"nav-wrapper\">\r\n");
      out.write("    \t\t<ul class=\"main-nav\">\r\n");
      out.write("\t        \t<li class=\"menu info\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/info/infoView\">병원소개</a></li>\r\n");
      out.write("\t        \t<li class=\"menu reservation\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/reservation/step1Reservation\">진료예약</a></li>\r\n");
      out.write("\t        \t<li class=\"menu notice\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/notice/noticeList\">공지사항</a></li>\r\n");
      out.write("\t        \t<li class=\"menu review\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/review/reviewList\">진료후기</a></li>\r\n");
      out.write("\t        \t");
if(!isLogin){ 
      out.write("\r\n");
      out.write("\t\t        \t<li class=\"menu login\" id=\"partition\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/common/login\">로그인</a></li>\r\n");
      out.write("\t\t        \t<li class=\"menu join\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/patient/join\">회원가입</a></li>\r\n");
      out.write("\t\t        ");
} else { 
      out.write("\r\n");
      out.write("\t\t        \t<li id=\"partition\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/common/logout\">로그아웃</a></li>\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \t");
 if("patient".equals(loginType) && loginPatient !=null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu mypage\">\t\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.print(loginType );
      out.write('/');
      out.print(loginType );
      out.write("Mypage?userId=");
      out.print(loginPatient.getPatientId() );
      out.write("\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t");
} else if("doctor".equals(loginType) && loginDoctor !=null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu mypage\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.print(loginType );
      out.write('/');
      out.print(loginType );
      out.write("Mypage?userId=");
      out.print(loginDoctor.getDoctorId() );
      out.write("\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t");
}else if("admin".equals(loginType) && loginAdmin !=null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu mypage\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.print(loginType );
      out.write("/patientList\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("    \t\t</ul>\r\n");
      out.write("    \t\t<hr>\r\n");
      out.write("  \t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<section id=\"content-section\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Doctor d = (Doctor)request.getAttribute("doctor");
	String profile = d.getDoctorProfile();
	String etc = profile.substring(profile.lastIndexOf("."));
	
	if(!profile.equals(d.getDoctorId())){
		profile= profile.substring(0,d.getDoctorId().length())+etc;
	}
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div id=\"subnav-wrapper\">\r\n");
      out.write("   <span id=\"subnav-title\">마이페이지</span>\r\n");
      out.write("   <div id=\"sub_menu\">\r\n");
      out.write("\t\t<p class=\"submenu patientList\"><a href=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.print(loginType );
      out.write("/patientList\">환자 관리</a></p>\r\n");
      out.write("\t\t<p class=\"submenu doctorList\"><a href=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.print(loginType );
      out.write("/doctorList\">의사 관리</a></p>\r\n");
      out.write("\t\t<p class=\"submenu adminView\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/adminView\">관리자정보</a></p>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 유효성 검사  -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction fn_updateVaildate(){\r\n");
      out.write("\t\tvar fileName = $(\"[name=up_file]\").val();\r\n");
      out.write("\t\tvar doctorId = $(\"#userId\").val();\r\n");
      out.write("\t\tvar result= fileName.substring(fileName.lastIndexOf(\"\\\\\")+1,fileName.lastIndexOf(\".\"));\r\n");
      out.write("\t\tvar resultJPG = result+\".JPG\";\r\n");
      out.write("\t\tvar resultPNG = result+\".PNG\";\r\n");
      out.write("\t\tvar checkNameJPG = doctorId+\".JPG\";\r\n");
      out.write("\t\tvar checkNamePNG = doctorId+\".PNG\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(result!=\"\" && checkNameJPG!=resultJPG\r\n");
      out.write("\t\t\t\t|| result!=\"\" && checkNamePNG!=resultPNG){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(\"파일이름은 아이디와 동일하게! 확장자는 JPG,PNG 만 가능\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 비밀번호 변경 팝업, 회원탈퇴 -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction fn_update_password(){\r\n");
      out.write("\t\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/doctor/updatePassword\";\t\r\n");
      out.write("\t\tvar title = \"updatePassword\";\r\n");
      out.write("\t\tvar status = \"left=500px, top=200px, width=400px, height=210px\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar userId = $(\"#userId\").val().trim();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar popup = window.open(url,title,status);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar updatePasswordFrm = document.updatePasswordFrm;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tupdatePasswordFrm.userId.value = userId;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//팝업과 form연결\r\n");
      out.write("\t\tupdatePasswordFrm.target = title;\r\n");
      out.write("\t\tupdatePasswordFrm.action = url;\r\n");
      out.write("\t\tupdatePasswordFrm.submit();\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"[name=up_file]\").change(function(){\r\n");
      out.write("\t\t\t//$(this).val()은 선택한 파일명\r\n");
      out.write("\t\t\tif($(this).val()==\"\"){\r\n");
      out.write("\t\t\t\t$(\"#fname\").show();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#fname\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction fn_delete(){\r\n");
      out.write("\t\tconfirm(\"정말로 탈퇴를 진행하시겠습니까..?\") ? location.href='");
      out.print(request.getContextPath());
      out.write("/admin/doctorDeleteEnd?id=");
      out.print(d.getDoctorId());
      out.write("' : \"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"content-wrapper\">\r\n");
      out.write("\t<form name=\"doctor_update_form\" action=\"");
      out.print(request.getContextPath());
      out.write("/doctor/updateEnd\" method=\"post\" enctype=\"multipart/form-data\" onsubmit=\"return fn_updateVaildate();\">\r\n");
      out.write("\t\t<table id=\"tbl-update\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\"><h3>개인정보 변경</h3></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>이 름 : </td>\r\n");
      out.write("                <td><input type=\"text\" id=\"userName\" name=\"userName\" value=\"");
      out.print(d.getDoctorName() );
      out.write("\" readOnly></td>\r\n");
      out.write("\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>아이디 : </td>\r\n");
      out.write("                <td><input type=\"text\" id=\"userId\" name=\"userId\" value=\"");
      out.print(d.getDoctorId() );
      out.write("\" readOnly></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("             <tr>\r\n");
      out.write("                <td>파트명</td>\r\n");
      out.write("                <td>\r\n");
      out.write("               \t\t<select name=\"partName\">\r\n");
      out.write("               \t\t\t<optgroup label=\"외과\">\r\n");
      out.write("               \t\t\t\t<option value=\"정형외과\" ");
      out.print("정형외과".equals(d.getPartName())?"selected":"");
      out.write(">정형외과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"신경외과\" ");
      out.print("신경외과".equals(d.getPartName())?"selected":"");
      out.write(">신경외과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"흉부외과\" ");
      out.print("흉부외과".equals(d.getPartName())?"selected":"");
      out.write(">흉부외과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"가정의학과\" ");
      out.print("가정의학과".equals(d.getPartName())?"selected":"");
      out.write(">가정의학과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"산부인과\" ");
      out.print("산부외과".equals(d.getPartName())?"selected":"");
      out.write(">산부인과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"성형외과\" ");
      out.print("성형외과".equals(d.getPartName())?"selected":"");
      out.write(">성형외과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"비뇨기과\" ");
      out.print("비뇨기과".equals(d.getPartName())?"selected":"");
      out.write(">비뇨기과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"피부과\" ");
      out.print("피부과".equals(d.getPartName())?"selected":"");
      out.write(">피부과</option>\r\n");
      out.write("               \t\t\t</optgroup>\r\n");
      out.write("               \t\t\t<optgroup label=\"내과\">\r\n");
      out.write("               \t\t\t\t<option value=\"안과\" ");
      out.print("안과".equals(d.getPartName())?"selected":"");
      out.write(">안과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"치과\" ");
      out.print("치과".equals(d.getPartName())?"selected":"");
      out.write(">치과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"일반내과\" ");
      out.print("일반내과".equals(d.getPartName())?"selected":"");
      out.write(">일반내과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"호흡기내과\" ");
      out.print("호흡기내과".equals(d.getPartName())?"selected":"");
      out.write(">호흡기내과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"소화내과\" ");
      out.print("소화내과".equals(d.getPartName())?"selected":"");
      out.write(">소화외과</option>\r\n");
      out.write("               \t\t\t\t<option value=\"신장내과\" ");
      out.print("신장내과".equals(d.getPartName())?"selected":"");
      out.write(">신장외과</option>\r\n");
      out.write("               \t\t\t</optgroup>\r\n");
      out.write("               \t\t</select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>프로필사진 </td>\r\n");
      out.write("\t\t\t\t<td style=\"position:relative;\">\r\n");
      out.write("\t\t\t\t\t");
if(d.getDoctorProfile()!=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 파일태그에 value속성은 임의로 변경할 수 없음 -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" name=\"up_file\"/>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"fname\">");
      out.print(profile );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t<!-- 파일변경대비 기존파일이름 필드 -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"old_file\" value=\"");
      out.print(d.getDoctorProfile());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t");
}else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" name=\"up_file\"/>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("                \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>전화번호</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"phone\" value=\"");
      out.print(d.getPhone());
      out.write("\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>주소</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"address\" value=\"");
      out.print(d.getAddress());
      out.write("\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td colspan=\"2\">\r\n");
      out.write("              \t<span>\r\n");
      out.write("\t              \t<input  type=\"submit\" value=\"수정\">&nbsp;\r\n");
      out.write("\t\t    \t  \t<input  type=\"button\" value=\"비밀번호변경\" onclick=\"fn_update_password();\"> &nbsp;\r\n");
      out.write("\t\t    \t  \t<input type=\"button\" value=\"탈퇴\" onclick=\"fn_delete();\" /> \r\n");
      out.write("\t    \t  \t</span>\r\n");
      out.write("\t    \t  </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </form>   \r\n");
      out.write("      <form name=\"updatePasswordFrm\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"userId\" />\r\n");
      out.write("\t  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<footer id = \"footer\">\r\n");
      out.write("\t\t<img class=\"footer-logo\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" alt=\"logo_panacea\">\r\n");
      out.write("\t\t<h3 id=\"footer-title\">Panacea</h3>\r\n");
      out.write("\t    &nbsp;&nbsp;\r\n");
      out.write("\t    <p id = \"footer-content\">\r\n");
      out.write("\t    \t강남구 역삼동 파나시아병원 <br />\r\n");
      out.write("\t    \t ⓒPanacia Corp.\r\n");
      out.write("\t    </p>\r\n");
      out.write("\t           \r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
